/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Feature Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getAttributeType <em>Attribute Type</em>}</li>
 * </ul>
 *
 * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getAttributeFeatureType()
 * @model
 * @generated
 */
public interface AttributeFeatureType extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attribute Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Type</em>' reference.
   * @see #setAttributeType(Attribute)
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getAttributeFeatureType_AttributeType()
   * @model
   * @generated
   */
  Attribute getAttributeType();

  /**
   * Sets the value of the '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getAttributeType <em>Attribute Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Type</em>' reference.
   * @see #getAttributeType()
   * @generated
   */
  void setAttributeType(Attribute value);

} // AttributeFeatureType
