/**
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext.ulmDsl2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getName <em>Name</em>}</li>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getVersion <em>Version</em>}</li>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getLookups <em>Lookups</em>}</li>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getEntities <em>Entities</em>}</li>
 * </ul>
 *
 * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext()
 * @model
 * @generated
 */
public interface Context extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Version</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.ulm.metaulm.xtext.ulmDsl2.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Lookups</b></em>' containment reference list.
   * The list contents are of type {@link org.ulm.metaulm.xtext.ulmDsl2.Lookup}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lookups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lookups</em>' containment reference list.
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext_Lookups()
   * @model containment="true"
   * @generated
   */
  EList<Lookup> getLookups();

  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link org.ulm.metaulm.xtext.ulmDsl2.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getContext_Entities()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getEntities();

} // Context
