/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Feature Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getEntityType <em>Entity Type</em>}</li>
 * </ul>
 *
 * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getEntityFeatureType()
 * @model
 * @generated
 */
public interface EntityFeatureType extends EObject
{
  /**
   * Returns the value of the '<em><b>Entity Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Type</em>' reference.
   * @see #setEntityType(Entity)
   * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package#getEntityFeatureType_EntityType()
   * @model
   * @generated
   */
  Entity getEntityType();

  /**
   * Sets the value of the '{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getEntityType <em>Entity Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Type</em>' reference.
   * @see #getEntityType()
   * @generated
   */
  void setEntityType(Entity value);

} // EntityFeatureType
