/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Factory
 * @model kind="package"
 * @generated
 */
public interface UlmDsl2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ulmDsl2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://org.mycorp/ulm/metaulm/xtext/UlmDsl2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ulmDsl2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UlmDsl2Package eINSTANCE = org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl.init();

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.ModelImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTEXTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.ContextImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NAME = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__VERSION = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__ATTRIBUTES = 2;

  /**
   * The feature id for the '<em><b>Lookups</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__LOOKUPS = 3;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__ENTITIES = 4;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__DESC = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeType()
   * @generated
   */
  int ATTRIBUTE_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Attribute Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeStringTypeImpl <em>Attribute String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeStringTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeStringType()
   * @generated
   */
  int ATTRIBUTE_STRING_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_STRING_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_STRING_TYPE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_STRING_TYPE__LENGTH = 2;

  /**
   * The number of structural features of the '<em>Attribute String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_STRING_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeDecimalTypeImpl <em>Attribute Decimal Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeDecimalTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeDecimalType()
   * @generated
   */
  int ATTRIBUTE_DECIMAL_TYPE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECIMAL_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECIMAL_TYPE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECIMAL_TYPE__SCALE = 2;

  /**
   * The feature id for the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECIMAL_TYPE__PRECISION = 3;

  /**
   * The number of structural features of the '<em>Attribute Decimal Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECIMAL_TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.EntityImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 1;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__DESC = 2;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__SUPER_TYPE = 3;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FEATURES = 4;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 7;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__MANDATORY = 1;

  /**
   * The feature id for the '<em><b>Identifier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__IDENTIFIER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 3;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureTypeImpl <em>Feature Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getFeatureType()
   * @generated
   */
  int FEATURE_TYPE = 8;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_TYPE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Feature Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl <em>Attribute Feature Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeFeatureType()
   * @generated
   */
  int ATTRIBUTE_FEATURE_TYPE = 9;

  /**
   * The feature id for the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE = 0;

  /**
   * The feature id for the '<em><b>Lookup</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_TYPE__LOOKUP = 1;

  /**
   * The number of structural features of the '<em>Attribute Feature Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.EntityFeatureTypeImpl <em>Entity Feature Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.EntityFeatureTypeImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getEntityFeatureType()
   * @generated
   */
  int ENTITY_FEATURE_TYPE = 10;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_TYPE__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_TYPE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_TYPE__LENGTH = 2;

  /**
   * The number of structural features of the '<em>Entity Feature Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupImpl <em>Lookup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookup()
   * @generated
   */
  int LOOKUP = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP__TYPE = 1;

  /**
   * The number of structural features of the '<em>Lookup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntImpl <em>Lookup Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupInt()
   * @generated
   */
  int LOOKUP_INT = 12;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT__DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT__VALUES = 1;

  /**
   * The number of structural features of the '<em>Lookup Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringImpl <em>Lookup String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupString()
   * @generated
   */
  int LOOKUP_STRING = 13;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING__DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING__VALUES = 1;

  /**
   * The number of structural features of the '<em>Lookup String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntValueImpl <em>Lookup Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntValueImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupIntValue()
   * @generated
   */
  int LOOKUP_INT_VALUE = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT_VALUE__VALUE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT_VALUE__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Lookup Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_INT_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringValueImpl <em>Lookup String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringValueImpl
   * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupStringValue()
   * @generated
   */
  int LOOKUP_STRING_VALUE = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING_VALUE__VALUE = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING_VALUE__DESCRIPTION = 1;

  /**
   * The number of structural features of the '<em>Lookup String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOKUP_STRING_VALUE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.Model#getContexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contexts</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Model#getContexts()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Contexts();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context#getName()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Name();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context#getVersion()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Version();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context#getAttributes()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getLookups <em>Lookups</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lookups</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context#getLookups()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Lookups();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.Context#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Context#getEntities()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Entities();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.ulm.metaulm.xtext.ulmDsl2.Attribute#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Attribute#getType()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Type();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Attribute#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Desc</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Attribute#getDesc()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Desc();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeType <em>Attribute Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeType
   * @generated
   */
  EClass getAttributeType();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeType#getName()
   * @see #getAttributeType()
   * @generated
   */
  EAttribute getAttributeType_Name();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType <em>Attribute String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute String Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType
   * @generated
   */
  EClass getAttributeStringType();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#getName()
   * @see #getAttributeStringType()
   * @generated
   */
  EAttribute getAttributeStringType_Name();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#isArray()
   * @see #getAttributeStringType()
   * @generated
   */
  EAttribute getAttributeStringType_Array();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeStringType#getLength()
   * @see #getAttributeStringType()
   * @generated
   */
  EAttribute getAttributeStringType_Length();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType <em>Attribute Decimal Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Decimal Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType
   * @generated
   */
  EClass getAttributeDecimalType();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getName()
   * @see #getAttributeDecimalType()
   * @generated
   */
  EAttribute getAttributeDecimalType_Name();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#isArray()
   * @see #getAttributeDecimalType()
   * @generated
   */
  EAttribute getAttributeDecimalType_Array();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getScale <em>Scale</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scale</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getScale()
   * @see #getAttributeDecimalType()
   * @generated
   */
  EAttribute getAttributeDecimalType_Scale();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getPrecision <em>Precision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Precision</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeDecimalType#getPrecision()
   * @see #getAttributeDecimalType()
   * @generated
   */
  EAttribute getAttributeDecimalType_Precision();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity#getType()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Type();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Desc</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity#getDesc()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Desc();

  /**
   * Returns the meta object for the reference '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity#getSuperType()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_SuperType();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.Entity#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Entity#getFeatures()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Features();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the containment reference '{@link org.ulm.metaulm.xtext.ulmDsl2.Feature#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Feature#getType()
   * @see #getFeature()
   * @generated
   */
  EReference getFeature_Type();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Feature#isMandatory <em>Mandatory</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mandatory</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Feature#isMandatory()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Mandatory();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Feature#isIdentifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifier</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Feature#isIdentifier()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Identifier();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.FeatureType <em>Feature Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.FeatureType
   * @generated
   */
  EClass getFeatureType();

  /**
   * Returns the meta object for the containment reference '{@link org.ulm.metaulm.xtext.ulmDsl2.FeatureType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.FeatureType#getType()
   * @see #getFeatureType()
   * @generated
   */
  EReference getFeatureType_Type();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType <em>Attribute Feature Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Feature Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType
   * @generated
   */
  EClass getAttributeFeatureType();

  /**
   * Returns the meta object for the reference '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getAttribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Attribute</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getAttribute()
   * @see #getAttributeFeatureType()
   * @generated
   */
  EReference getAttributeFeatureType_Attribute();

  /**
   * Returns the meta object for the reference '{@link org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getLookup <em>Lookup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lookup</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType#getLookup()
   * @see #getAttributeFeatureType()
   * @generated
   */
  EReference getAttributeFeatureType_Lookup();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType <em>Entity Feature Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Feature Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType
   * @generated
   */
  EClass getEntityFeatureType();

  /**
   * Returns the meta object for the reference '{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getEntity()
   * @see #getEntityFeatureType()
   * @generated
   */
  EReference getEntityFeatureType_Entity();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#isArray()
   * @see #getEntityFeatureType()
   * @generated
   */
  EAttribute getEntityFeatureType_Array();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.EntityFeatureType#getLength()
   * @see #getEntityFeatureType()
   * @generated
   */
  EAttribute getEntityFeatureType_Length();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.Lookup <em>Lookup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Lookup
   * @generated
   */
  EClass getLookup();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.Lookup#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Lookup#getName()
   * @see #getLookup()
   * @generated
   */
  EAttribute getLookup_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.ulm.metaulm.xtext.ulmDsl2.Lookup#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.Lookup#getType()
   * @see #getLookup()
   * @generated
   */
  EReference getLookup_Type();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupInt <em>Lookup Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup Int</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupInt
   * @generated
   */
  EClass getLookupInt();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupInt#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupInt#getDescription()
   * @see #getLookupInt()
   * @generated
   */
  EAttribute getLookupInt_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupInt#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupInt#getValues()
   * @see #getLookupInt()
   * @generated
   */
  EReference getLookupInt_Values();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupString <em>Lookup String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup String</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupString
   * @generated
   */
  EClass getLookupString();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupString#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupString#getDescription()
   * @see #getLookupString()
   * @generated
   */
  EAttribute getLookupString_Description();

  /**
   * Returns the meta object for the containment reference list '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupString#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupString#getValues()
   * @see #getLookupString()
   * @generated
   */
  EReference getLookupString_Values();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue <em>Lookup Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup Int Value</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue
   * @generated
   */
  EClass getLookupIntValue();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue#getValue()
   * @see #getLookupIntValue()
   * @generated
   */
  EAttribute getLookupIntValue_Value();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupIntValue#getDescription()
   * @see #getLookupIntValue()
   * @generated
   */
  EAttribute getLookupIntValue_Description();

  /**
   * Returns the meta object for class '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue <em>Lookup String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lookup String Value</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue
   * @generated
   */
  EClass getLookupStringValue();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue#getValue()
   * @see #getLookupStringValue()
   * @generated
   */
  EAttribute getLookupStringValue_Value();

  /**
   * Returns the meta object for the attribute '{@link org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.ulm.metaulm.xtext.ulmDsl2.LookupStringValue#getDescription()
   * @see #getLookupStringValue()
   * @generated
   */
  EAttribute getLookupStringValue_Description();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UlmDsl2Factory getUlmDsl2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.ModelImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONTEXTS = eINSTANCE.getModel_Contexts();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.ContextImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NAME = eINSTANCE.getContext_Name();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__VERSION = eINSTANCE.getContext_Version();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__ATTRIBUTES = eINSTANCE.getContext_Attributes();

    /**
     * The meta object literal for the '<em><b>Lookups</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__LOOKUPS = eINSTANCE.getContext_Lookups();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__ENTITIES = eINSTANCE.getContext_Entities();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__TYPE = eINSTANCE.getAttribute_Type();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__DESC = eINSTANCE.getAttribute_Desc();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeTypeImpl <em>Attribute Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeType()
     * @generated
     */
    EClass ATTRIBUTE_TYPE = eINSTANCE.getAttributeType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_TYPE__NAME = eINSTANCE.getAttributeType_Name();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeStringTypeImpl <em>Attribute String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeStringTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeStringType()
     * @generated
     */
    EClass ATTRIBUTE_STRING_TYPE = eINSTANCE.getAttributeStringType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_STRING_TYPE__NAME = eINSTANCE.getAttributeStringType_Name();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_STRING_TYPE__ARRAY = eINSTANCE.getAttributeStringType_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_STRING_TYPE__LENGTH = eINSTANCE.getAttributeStringType_Length();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeDecimalTypeImpl <em>Attribute Decimal Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeDecimalTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeDecimalType()
     * @generated
     */
    EClass ATTRIBUTE_DECIMAL_TYPE = eINSTANCE.getAttributeDecimalType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_DECIMAL_TYPE__NAME = eINSTANCE.getAttributeDecimalType_Name();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_DECIMAL_TYPE__ARRAY = eINSTANCE.getAttributeDecimalType_Array();

    /**
     * The meta object literal for the '<em><b>Scale</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_DECIMAL_TYPE__SCALE = eINSTANCE.getAttributeDecimalType_Scale();

    /**
     * The meta object literal for the '<em><b>Precision</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_DECIMAL_TYPE__PRECISION = eINSTANCE.getAttributeDecimalType_Precision();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.EntityImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__TYPE = eINSTANCE.getEntity_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__DESC = eINSTANCE.getEntity_Desc();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__SUPER_TYPE = eINSTANCE.getEntity_SuperType();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FEATURES = eINSTANCE.getEntity_Features();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE__TYPE = eINSTANCE.getFeature_Type();

    /**
     * The meta object literal for the '<em><b>Mandatory</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__MANDATORY = eINSTANCE.getFeature_Mandatory();

    /**
     * The meta object literal for the '<em><b>Identifier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__IDENTIFIER = eINSTANCE.getFeature_Identifier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureTypeImpl <em>Feature Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.FeatureTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getFeatureType()
     * @generated
     */
    EClass FEATURE_TYPE = eINSTANCE.getFeatureType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_TYPE__TYPE = eINSTANCE.getFeatureType_Type();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl <em>Attribute Feature Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getAttributeFeatureType()
     * @generated
     */
    EClass ATTRIBUTE_FEATURE_TYPE = eINSTANCE.getAttributeFeatureType();

    /**
     * The meta object literal for the '<em><b>Attribute</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE = eINSTANCE.getAttributeFeatureType_Attribute();

    /**
     * The meta object literal for the '<em><b>Lookup</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_FEATURE_TYPE__LOOKUP = eINSTANCE.getAttributeFeatureType_Lookup();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.EntityFeatureTypeImpl <em>Entity Feature Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.EntityFeatureTypeImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getEntityFeatureType()
     * @generated
     */
    EClass ENTITY_FEATURE_TYPE = eINSTANCE.getEntityFeatureType();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY_FEATURE_TYPE__ENTITY = eINSTANCE.getEntityFeatureType_Entity();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FEATURE_TYPE__ARRAY = eINSTANCE.getEntityFeatureType_Array();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FEATURE_TYPE__LENGTH = eINSTANCE.getEntityFeatureType_Length();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupImpl <em>Lookup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookup()
     * @generated
     */
    EClass LOOKUP = eINSTANCE.getLookup();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP__NAME = eINSTANCE.getLookup_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOKUP__TYPE = eINSTANCE.getLookup_Type();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntImpl <em>Lookup Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupInt()
     * @generated
     */
    EClass LOOKUP_INT = eINSTANCE.getLookupInt();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_INT__DESCRIPTION = eINSTANCE.getLookupInt_Description();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOKUP_INT__VALUES = eINSTANCE.getLookupInt_Values();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringImpl <em>Lookup String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupString()
     * @generated
     */
    EClass LOOKUP_STRING = eINSTANCE.getLookupString();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_STRING__DESCRIPTION = eINSTANCE.getLookupString_Description();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOKUP_STRING__VALUES = eINSTANCE.getLookupString_Values();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntValueImpl <em>Lookup Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupIntValueImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupIntValue()
     * @generated
     */
    EClass LOOKUP_INT_VALUE = eINSTANCE.getLookupIntValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_INT_VALUE__VALUE = eINSTANCE.getLookupIntValue_Value();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_INT_VALUE__DESCRIPTION = eINSTANCE.getLookupIntValue_Description();

    /**
     * The meta object literal for the '{@link org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringValueImpl <em>Lookup String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.LookupStringValueImpl
     * @see org.ulm.metaulm.xtext.ulmDsl2.impl.UlmDsl2PackageImpl#getLookupStringValue()
     * @generated
     */
    EClass LOOKUP_STRING_VALUE = eINSTANCE.getLookupStringValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_STRING_VALUE__VALUE = eINSTANCE.getLookupStringValue_Value();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOKUP_STRING_VALUE__DESCRIPTION = eINSTANCE.getLookupStringValue_Description();

  }

} //UlmDsl2Package
