/*
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.ulm.xtext2.ui.internal.Xtext2Activator;

public class UlmDsl2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Xtext2Activator.getInstance().getInjector("org.ulm.metaulm.xtext.UlmDsl2");
	}

}
