/**
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext.ide;

import org.ulm.metaulm.xtext.ide.AbstractUlmDsl2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class UlmDsl2IdeModule extends AbstractUlmDsl2IdeModule {
}
