/**
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.ulm.metaulm.xtext.UlmDsl2RuntimeModule;
import org.ulm.metaulm.xtext.UlmDsl2StandaloneSetup;
import org.ulm.metaulm.xtext.ide.UlmDsl2IdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class UlmDsl2IdeSetup extends UlmDsl2StandaloneSetup {
  @Override
  public Injector createInjector() {
    UlmDsl2RuntimeModule _ulmDsl2RuntimeModule = new UlmDsl2RuntimeModule();
    UlmDsl2IdeModule _ulmDsl2IdeModule = new UlmDsl2IdeModule();
    return Guice.createInjector(Modules2.mixin(_ulmDsl2RuntimeModule, _ulmDsl2IdeModule));
  }
}
