/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.ulm.metaulm.xtext.ulmDsl2.Attribute;
import org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType;
import org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Feature Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl#getAttributeType <em>Attribute Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeFeatureTypeImpl extends MinimalEObjectImpl.Container implements AttributeFeatureType
{
  /**
   * The cached value of the '{@link #getAttributeType() <em>Attribute Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttributeType()
   * @generated
   * @ordered
   */
  protected Attribute attributeType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeFeatureTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UlmDsl2Package.Literals.ATTRIBUTE_FEATURE_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute getAttributeType()
  {
    if (attributeType != null && attributeType.eIsProxy())
    {
      InternalEObject oldAttributeType = (InternalEObject)attributeType;
      attributeType = (Attribute)eResolveProxy(oldAttributeType);
      if (attributeType != oldAttributeType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE, oldAttributeType, attributeType));
      }
    }
    return attributeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttributeType()
  {
    return attributeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttributeType(Attribute newAttributeType)
  {
    Attribute oldAttributeType = attributeType;
    attributeType = newAttributeType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE, oldAttributeType, attributeType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE:
        if (resolve) return getAttributeType();
        return basicGetAttributeType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE:
        setAttributeType((Attribute)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE:
        setAttributeType((Attribute)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE_TYPE:
        return attributeType != null;
    }
    return super.eIsSet(featureID);
  }

} //AttributeFeatureTypeImpl
