/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.ulm.metaulm.xtext.ulmDsl2.Attribute;
import org.ulm.metaulm.xtext.ulmDsl2.AttributeFeatureType;
import org.ulm.metaulm.xtext.ulmDsl2.Lookup;
import org.ulm.metaulm.xtext.ulmDsl2.UlmDsl2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Feature Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.ulm.metaulm.xtext.ulmDsl2.impl.AttributeFeatureTypeImpl#getLookup <em>Lookup</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeFeatureTypeImpl extends MinimalEObjectImpl.Container implements AttributeFeatureType
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getLookup() <em>Lookup</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLookup()
   * @generated
   * @ordered
   */
  protected Lookup lookup;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeFeatureTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UlmDsl2Package.Literals.ATTRIBUTE_FEATURE_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lookup getLookup()
  {
    if (lookup != null && lookup.eIsProxy())
    {
      InternalEObject oldLookup = (InternalEObject)lookup;
      lookup = (Lookup)eResolveProxy(oldLookup);
      if (lookup != oldLookup)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP, oldLookup, lookup));
      }
    }
    return lookup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lookup basicGetLookup()
  {
    return lookup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLookup(Lookup newLookup)
  {
    Lookup oldLookup = lookup;
    lookup = newLookup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP, oldLookup, lookup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP:
        if (resolve) return getLookup();
        return basicGetLookup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP:
        setLookup((Lookup)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP:
        setLookup((Lookup)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__ATTRIBUTE:
        return attribute != null;
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE__LOOKUP:
        return lookup != null;
    }
    return super.eIsSet(featureID);
  }

} //AttributeFeatureTypeImpl
