/**
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.ulmDsl2.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.ulm.metaulm.xtext.ulmDsl2.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UlmDsl2FactoryImpl extends EFactoryImpl implements UlmDsl2Factory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static UlmDsl2Factory init()
  {
    try
    {
      UlmDsl2Factory theUlmDsl2Factory = (UlmDsl2Factory)EPackage.Registry.INSTANCE.getEFactory(UlmDsl2Package.eNS_URI);
      if (theUlmDsl2Factory != null)
      {
        return theUlmDsl2Factory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new UlmDsl2FactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UlmDsl2FactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case UlmDsl2Package.MODEL: return createModel();
      case UlmDsl2Package.CONTEXT: return createContext();
      case UlmDsl2Package.ATTRIBUTE: return createAttribute();
      case UlmDsl2Package.ATTRIBUTE_TYPE: return createAttributeType();
      case UlmDsl2Package.ATTRIBUTE_STRING_TYPE: return createAttributeStringType();
      case UlmDsl2Package.ATTRIBUTE_DECIMAL_TYPE: return createAttributeDecimalType();
      case UlmDsl2Package.ENTITY: return createEntity();
      case UlmDsl2Package.FEATURE: return createFeature();
      case UlmDsl2Package.FEATURE_TYPE: return createFeatureType();
      case UlmDsl2Package.ATTRIBUTE_FEATURE_TYPE: return createAttributeFeatureType();
      case UlmDsl2Package.ENTITY_FEATURE_TYPE: return createEntityFeatureType();
      case UlmDsl2Package.LOOKUP: return createLookup();
      case UlmDsl2Package.LOOKUP_INT: return createLookupInt();
      case UlmDsl2Package.LOOKUP_STRING: return createLookupString();
      case UlmDsl2Package.LOOKUP_INT_VALUE: return createLookupIntValue();
      case UlmDsl2Package.LOOKUP_STRING_VALUE: return createLookupStringValue();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Context createContext()
  {
    ContextImpl context = new ContextImpl();
    return context;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute createAttribute()
  {
    AttributeImpl attribute = new AttributeImpl();
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeType createAttributeType()
  {
    AttributeTypeImpl attributeType = new AttributeTypeImpl();
    return attributeType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeStringType createAttributeStringType()
  {
    AttributeStringTypeImpl attributeStringType = new AttributeStringTypeImpl();
    return attributeStringType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeDecimalType createAttributeDecimalType()
  {
    AttributeDecimalTypeImpl attributeDecimalType = new AttributeDecimalTypeImpl();
    return attributeDecimalType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Entity createEntity()
  {
    EntityImpl entity = new EntityImpl();
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Feature createFeature()
  {
    FeatureImpl feature = new FeatureImpl();
    return feature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FeatureType createFeatureType()
  {
    FeatureTypeImpl featureType = new FeatureTypeImpl();
    return featureType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AttributeFeatureType createAttributeFeatureType()
  {
    AttributeFeatureTypeImpl attributeFeatureType = new AttributeFeatureTypeImpl();
    return attributeFeatureType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EntityFeatureType createEntityFeatureType()
  {
    EntityFeatureTypeImpl entityFeatureType = new EntityFeatureTypeImpl();
    return entityFeatureType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lookup createLookup()
  {
    LookupImpl lookup = new LookupImpl();
    return lookup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LookupInt createLookupInt()
  {
    LookupIntImpl lookupInt = new LookupIntImpl();
    return lookupInt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LookupString createLookupString()
  {
    LookupStringImpl lookupString = new LookupStringImpl();
    return lookupString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LookupIntValue createLookupIntValue()
  {
    LookupIntValueImpl lookupIntValue = new LookupIntValueImpl();
    return lookupIntValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LookupStringValue createLookupStringValue()
  {
    LookupStringValueImpl lookupStringValue = new LookupStringValueImpl();
    return lookupStringValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UlmDsl2Package getUlmDsl2Package()
  {
    return (UlmDsl2Package)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static UlmDsl2Package getPackage()
  {
    return UlmDsl2Package.eINSTANCE;
  }

} //UlmDsl2FactoryImpl
