/*
 * generated by Xtext 2.14.0
 */
package org.ulm.metaulm.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class UlmDsl2GrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cContextsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cContextsContextParserRuleCall_3_0 = (RuleCall)cContextsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Model:
		//	'model' name=ID '{'
		//	contexts+=Context*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'model' name=ID '{' contexts+=Context* '}'
		public Group getGroup() { return cGroup; }
		
		//'model'
		public Keyword getModelKeyword_0() { return cModelKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//contexts+=Context*
		public Assignment getContextsAssignment_3() { return cContextsAssignment_3; }
		
		//Context
		public RuleCall getContextsContextParserRuleCall_3_0() { return cContextsContextParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ContextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Context");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cVersionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cVersionVersionParserRuleCall_2_0 = (RuleCall)cVersionAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAttributesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cAttributesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cAttributesAttributeParserRuleCall_4_2_0 = (RuleCall)cAttributesAssignment_4_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLookupsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLookupsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLookupsLookupParserRuleCall_5_2_0 = (RuleCall)cLookupsAssignment_5_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEntitiesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEntitiesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cEntitiesEntityParserRuleCall_6_2_0 = (RuleCall)cEntitiesAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Context:
		//	'context' name=ID version=Version '{' ('attributes' '{'
		//	attributes+=Attribute*
		//	'}')? ('lookups' '{'
		//	lookups+=Lookup*
		//	'}')? ('entities' '{'
		//	entities+=Entity*
		//	'}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'context' name=ID version=Version '{' ('attributes' '{' attributes+=Attribute* '}')? ('lookups' '{' lookups+=Lookup*
		//'}')? ('entities' '{' entities+=Entity* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'context'
		public Keyword getContextKeyword_0() { return cContextKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//version=Version
		public Assignment getVersionAssignment_2() { return cVersionAssignment_2; }
		
		//Version
		public RuleCall getVersionVersionParserRuleCall_2_0() { return cVersionVersionParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('attributes' '{' attributes+=Attribute* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'attributes'
		public Keyword getAttributesKeyword_4_0() { return cAttributesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//attributes+=Attribute*
		public Assignment getAttributesAssignment_4_2() { return cAttributesAssignment_4_2; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_4_2_0() { return cAttributesAttributeParserRuleCall_4_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_3() { return cRightCurlyBracketKeyword_4_3; }
		
		//('lookups' '{' lookups+=Lookup* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'lookups'
		public Keyword getLookupsKeyword_5_0() { return cLookupsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//lookups+=Lookup*
		public Assignment getLookupsAssignment_5_2() { return cLookupsAssignment_5_2; }
		
		//Lookup
		public RuleCall getLookupsLookupParserRuleCall_5_2_0() { return cLookupsLookupParserRuleCall_5_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_3() { return cRightCurlyBracketKeyword_5_3; }
		
		//('entities' '{' entities+=Entity* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'entities'
		public Keyword getEntitiesKeyword_6_0() { return cEntitiesKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//entities+=Entity*
		public Assignment getEntitiesAssignment_6_2() { return cEntitiesAssignment_6_2; }
		
		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_6_2_0() { return cEntitiesEntityParserRuleCall_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_3() { return cRightCurlyBracketKeyword_6_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class VersionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Version");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//Version:
		//	INT '.' INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeAlternatives_1_0 = (Alternatives)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeAttributeTypeParserRuleCall_1_0_0 = (RuleCall)cTypeAlternatives_1_0.eContents().get(0);
		private final RuleCall cTypeAttributeStringTypeParserRuleCall_1_0_1 = (RuleCall)cTypeAlternatives_1_0.eContents().get(1);
		private final RuleCall cTypeAttributeDecimalTypeParserRuleCall_1_0_2 = (RuleCall)cTypeAlternatives_1_0.eContents().get(2);
		private final Assignment cDescAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Attribute:
		//	name=ID type=(AttributeType | AttributeStringType | AttributeDecimalType) desc=STRING? ';';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID type=(AttributeType | AttributeStringType | AttributeDecimalType) desc=STRING? ';'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//type=(AttributeType | AttributeStringType | AttributeDecimalType)
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//(AttributeType | AttributeStringType | AttributeDecimalType)
		public Alternatives getTypeAlternatives_1_0() { return cTypeAlternatives_1_0; }
		
		//AttributeType
		public RuleCall getTypeAttributeTypeParserRuleCall_1_0_0() { return cTypeAttributeTypeParserRuleCall_1_0_0; }
		
		//AttributeStringType
		public RuleCall getTypeAttributeStringTypeParserRuleCall_1_0_1() { return cTypeAttributeStringTypeParserRuleCall_1_0_1; }
		
		//AttributeDecimalType
		public RuleCall getTypeAttributeDecimalTypeParserRuleCall_1_0_2() { return cTypeAttributeDecimalTypeParserRuleCall_1_0_2; }
		
		//desc=STRING?
		public Assignment getDescAssignment_2() { return cDescAssignment_2; }
		
		//STRING
		public RuleCall getDescSTRINGTerminalRuleCall_2_0() { return cDescSTRINGTerminalRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class AttributeTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.AttributeType");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cNameAlternatives_0 = (Alternatives)cNameAssignment.eContents().get(0);
		private final Keyword cNameIntKeyword_0_0 = (Keyword)cNameAlternatives_0.eContents().get(0);
		private final Keyword cNameBooleanKeyword_0_1 = (Keyword)cNameAlternatives_0.eContents().get(1);
		private final Keyword cNameDateKeyword_0_2 = (Keyword)cNameAlternatives_0.eContents().get(2);
		private final Keyword cNameDatetimeKeyword_0_3 = (Keyword)cNameAlternatives_0.eContents().get(3);
		private final Keyword cNameTimestampKeyword_0_4 = (Keyword)cNameAlternatives_0.eContents().get(4);
		
		//AttributeType:
		//	name=('int' | 'boolean' | 'date' | 'datetime' | 'timestamp');
		@Override public ParserRule getRule() { return rule; }
		
		//name=('int' | 'boolean' | 'date' | 'datetime' | 'timestamp')
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//('int' | 'boolean' | 'date' | 'datetime' | 'timestamp')
		public Alternatives getNameAlternatives_0() { return cNameAlternatives_0; }
		
		//'int'
		public Keyword getNameIntKeyword_0_0() { return cNameIntKeyword_0_0; }
		
		//'boolean'
		public Keyword getNameBooleanKeyword_0_1() { return cNameBooleanKeyword_0_1; }
		
		//'date'
		public Keyword getNameDateKeyword_0_2() { return cNameDateKeyword_0_2; }
		
		//'datetime'
		public Keyword getNameDatetimeKeyword_0_3() { return cNameDatetimeKeyword_0_3; }
		
		//'timestamp'
		public Keyword getNameTimestampKeyword_0_4() { return cNameTimestampKeyword_0_4; }
	}
	public class AttributeStringTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.AttributeStringType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameStringKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cArrayAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cArrayLeftSquareBracketKeyword_1_0_0 = (Keyword)cArrayAssignment_1_0.eContents().get(0);
		private final Assignment cLengthAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cLengthINTTerminalRuleCall_1_1_0 = (RuleCall)cLengthAssignment_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//AttributeStringType:
		//	name='string' (array?='[' length=INT ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='string' (array?='[' length=INT ']')?
		public Group getGroup() { return cGroup; }
		
		//name='string'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'string'
		public Keyword getNameStringKeyword_0_0() { return cNameStringKeyword_0_0; }
		
		//(array?='[' length=INT ']')?
		public Group getGroup_1() { return cGroup_1; }
		
		//array?='['
		public Assignment getArrayAssignment_1_0() { return cArrayAssignment_1_0; }
		
		//'['
		public Keyword getArrayLeftSquareBracketKeyword_1_0_0() { return cArrayLeftSquareBracketKeyword_1_0_0; }
		
		//length=INT
		public Assignment getLengthAssignment_1_1() { return cLengthAssignment_1_1; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_1_1_0() { return cLengthINTTerminalRuleCall_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_1_2() { return cRightSquareBracketKeyword_1_2; }
	}
	public class AttributeDecimalTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.AttributeDecimalType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameDecimalKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cArrayAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cArrayLeftSquareBracketKeyword_1_0_0 = (Keyword)cArrayAssignment_1_0.eContents().get(0);
		private final Assignment cScaleAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cScaleINTTerminalRuleCall_1_1_0 = (RuleCall)cScaleAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cPrecisionAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cPrecisionINTTerminalRuleCall_1_2_1_0 = (RuleCall)cPrecisionAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//AttributeDecimalType:
		//	name='decimal' (array?='[' scale=INT (',' precision=INT)? ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name='decimal' (array?='[' scale=INT (',' precision=INT)? ']')?
		public Group getGroup() { return cGroup; }
		
		//name='decimal'
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//'decimal'
		public Keyword getNameDecimalKeyword_0_0() { return cNameDecimalKeyword_0_0; }
		
		//(array?='[' scale=INT (',' precision=INT)? ']')?
		public Group getGroup_1() { return cGroup_1; }
		
		//array?='['
		public Assignment getArrayAssignment_1_0() { return cArrayAssignment_1_0; }
		
		//'['
		public Keyword getArrayLeftSquareBracketKeyword_1_0_0() { return cArrayLeftSquareBracketKeyword_1_0_0; }
		
		//scale=INT
		public Assignment getScaleAssignment_1_1() { return cScaleAssignment_1_1; }
		
		//INT
		public RuleCall getScaleINTTerminalRuleCall_1_1_0() { return cScaleINTTerminalRuleCall_1_1_0; }
		
		//(',' precision=INT)?
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//precision=INT
		public Assignment getPrecisionAssignment_1_2_1() { return cPrecisionAssignment_1_2_1; }
		
		//INT
		public RuleCall getPrecisionINTTerminalRuleCall_1_2_1_0() { return cPrecisionINTTerminalRuleCall_1_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_1_3() { return cRightSquareBracketKeyword_1_3; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Alternatives cTypeAlternatives_0_0 = (Alternatives)cTypeAssignment_0.eContents().get(0);
		private final Keyword cTypeDataKeyword_0_0_0 = (Keyword)cTypeAlternatives_0_0.eContents().get(0);
		private final Keyword cTypeStaticKeyword_0_0_1 = (Keyword)cTypeAlternatives_0_0.eContents().get(1);
		private final Keyword cTypeLookupKeyword_0_0_2 = (Keyword)cTypeAlternatives_0_0.eContents().get(2);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cDescAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDescSTRINGTerminalRuleCall_2_0 = (RuleCall)cDescAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cExtendsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSuperTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cSuperTypeEntityCrossReference_3_1_0 = (CrossReference)cSuperTypeAssignment_3_1.eContents().get(0);
		private final RuleCall cSuperTypeEntityIDTerminalRuleCall_3_1_0_1 = (RuleCall)cSuperTypeEntityCrossReference_3_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFeaturesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFeaturesFeatureParserRuleCall_5_0 = (RuleCall)cFeaturesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Entity:
		//	type=('data' | 'static' | 'lookup')? name=ID desc=STRING? ('extends' superType=[Entity])? '{'
		//	features+=Feature*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//type=('data' | 'static' | 'lookup')? name=ID desc=STRING? ('extends' superType=[Entity])? '{' features+=Feature* '}'
		public Group getGroup() { return cGroup; }
		
		//type=('data' | 'static' | 'lookup')?
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//('data' | 'static' | 'lookup')
		public Alternatives getTypeAlternatives_0_0() { return cTypeAlternatives_0_0; }
		
		//'data'
		public Keyword getTypeDataKeyword_0_0_0() { return cTypeDataKeyword_0_0_0; }
		
		//'static'
		public Keyword getTypeStaticKeyword_0_0_1() { return cTypeStaticKeyword_0_0_1; }
		
		//'lookup'
		public Keyword getTypeLookupKeyword_0_0_2() { return cTypeLookupKeyword_0_0_2; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//desc=STRING?
		public Assignment getDescAssignment_2() { return cDescAssignment_2; }
		
		//STRING
		public RuleCall getDescSTRINGTerminalRuleCall_2_0() { return cDescSTRINGTerminalRuleCall_2_0; }
		
		//('extends' superType=[Entity])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'extends'
		public Keyword getExtendsKeyword_3_0() { return cExtendsKeyword_3_0; }
		
		//superType=[Entity]
		public Assignment getSuperTypeAssignment_3_1() { return cSuperTypeAssignment_3_1; }
		
		//[Entity]
		public CrossReference getSuperTypeEntityCrossReference_3_1_0() { return cSuperTypeEntityCrossReference_3_1_0; }
		
		//ID
		public RuleCall getSuperTypeEntityIDTerminalRuleCall_3_1_0_1() { return cSuperTypeEntityIDTerminalRuleCall_3_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//features+=Feature*
		public Assignment getFeaturesAssignment_5() { return cFeaturesAssignment_5; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_5_0() { return cFeaturesFeatureParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeFeatureTypeParserRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cMandatoryAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cMandatoryMandatoryKeyword_1_0 = (Keyword)cMandatoryAssignment_1.eContents().get(0);
		private final Assignment cIdentifierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cIdentifierIdentifierKeyword_2_0 = (Keyword)cIdentifierAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Feature:
		//	type=FeatureType
		//	mandatory?='mandatory'?
		//	identifier?='identifier'? ('as' name=ID)?
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//type=FeatureType mandatory?='mandatory'? identifier?='identifier'? ('as' name=ID)? ';'
		public Group getGroup() { return cGroup; }
		
		//type=FeatureType
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//FeatureType
		public RuleCall getTypeFeatureTypeParserRuleCall_0_0() { return cTypeFeatureTypeParserRuleCall_0_0; }
		
		//mandatory?='mandatory'?
		public Assignment getMandatoryAssignment_1() { return cMandatoryAssignment_1; }
		
		//'mandatory'
		public Keyword getMandatoryMandatoryKeyword_1_0() { return cMandatoryMandatoryKeyword_1_0; }
		
		//identifier?='identifier'?
		public Assignment getIdentifierAssignment_2() { return cIdentifierAssignment_2; }
		
		//'identifier'
		public Keyword getIdentifierIdentifierKeyword_2_0() { return cIdentifierIdentifierKeyword_2_0; }
		
		//('as' name=ID)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'as'
		public Keyword getAsKeyword_3_0() { return cAsKeyword_3_0; }
		
		//name=ID
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_1_0() { return cNameIDTerminalRuleCall_3_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}
	public class FeatureTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.FeatureType");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final Alternatives cTypeAlternatives_0 = (Alternatives)cTypeAssignment.eContents().get(0);
		private final RuleCall cTypeAttributeFeatureTypeParserRuleCall_0_0 = (RuleCall)cTypeAlternatives_0.eContents().get(0);
		private final RuleCall cTypeEntityFeatureTypeParserRuleCall_0_1 = (RuleCall)cTypeAlternatives_0.eContents().get(1);
		
		//FeatureType:
		//	type=(AttributeFeatureType | EntityFeatureType);
		@Override public ParserRule getRule() { return rule; }
		
		//type=(AttributeFeatureType | EntityFeatureType)
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//(AttributeFeatureType | EntityFeatureType)
		public Alternatives getTypeAlternatives_0() { return cTypeAlternatives_0; }
		
		//AttributeFeatureType
		public RuleCall getTypeAttributeFeatureTypeParserRuleCall_0_0() { return cTypeAttributeFeatureTypeParserRuleCall_0_0; }
		
		//EntityFeatureType
		public RuleCall getTypeEntityFeatureTypeParserRuleCall_0_1() { return cTypeEntityFeatureTypeParserRuleCall_0_1; }
	}
	public class AttributeFeatureTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.AttributeFeatureType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAttributeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAttributeAttributeCrossReference_0_0 = (CrossReference)cAttributeAssignment_0.eContents().get(0);
		private final RuleCall cAttributeAttributeIDTerminalRuleCall_0_0_1 = (RuleCall)cAttributeAttributeCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cBoundedKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cLookupAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cLookupLookupCrossReference_1_1_0 = (CrossReference)cLookupAssignment_1_1.eContents().get(0);
		private final RuleCall cLookupLookupIDTerminalRuleCall_1_1_0_1 = (RuleCall)cLookupLookupCrossReference_1_1_0.eContents().get(1);
		
		//AttributeFeatureType:
		//	attribute=[Attribute] ('bounded' lookup=[Lookup])?;
		@Override public ParserRule getRule() { return rule; }
		
		//attribute=[Attribute] ('bounded' lookup=[Lookup])?
		public Group getGroup() { return cGroup; }
		
		//attribute=[Attribute]
		public Assignment getAttributeAssignment_0() { return cAttributeAssignment_0; }
		
		//[Attribute]
		public CrossReference getAttributeAttributeCrossReference_0_0() { return cAttributeAttributeCrossReference_0_0; }
		
		//ID
		public RuleCall getAttributeAttributeIDTerminalRuleCall_0_0_1() { return cAttributeAttributeIDTerminalRuleCall_0_0_1; }
		
		//('bounded' lookup=[Lookup])?
		public Group getGroup_1() { return cGroup_1; }
		
		//'bounded'
		public Keyword getBoundedKeyword_1_0() { return cBoundedKeyword_1_0; }
		
		//lookup=[Lookup]
		public Assignment getLookupAssignment_1_1() { return cLookupAssignment_1_1; }
		
		//[Lookup]
		public CrossReference getLookupLookupCrossReference_1_1_0() { return cLookupLookupCrossReference_1_1_0; }
		
		//ID
		public RuleCall getLookupLookupIDTerminalRuleCall_1_1_0_1() { return cLookupLookupIDTerminalRuleCall_1_1_0_1; }
	}
	public class EntityFeatureTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.EntityFeatureType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cReferencesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEntityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEntityEntityCrossReference_1_0 = (CrossReference)cEntityAssignment_1.eContents().get(0);
		private final RuleCall cEntityEntityIDTerminalRuleCall_1_0_1 = (RuleCall)cEntityEntityCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cArrayAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Keyword cArrayLeftSquareBracketKeyword_2_0_0 = (Keyword)cArrayAssignment_2_0.eContents().get(0);
		private final Assignment cLengthAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cLengthINTTerminalRuleCall_2_1_0 = (RuleCall)cLengthAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//EntityFeatureType:
		//	'references' entity=[Entity] (array?='[' length=INT? ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'references' entity=[Entity] (array?='[' length=INT? ']')?
		public Group getGroup() { return cGroup; }
		
		//'references'
		public Keyword getReferencesKeyword_0() { return cReferencesKeyword_0; }
		
		//entity=[Entity]
		public Assignment getEntityAssignment_1() { return cEntityAssignment_1; }
		
		//[Entity]
		public CrossReference getEntityEntityCrossReference_1_0() { return cEntityEntityCrossReference_1_0; }
		
		//ID
		public RuleCall getEntityEntityIDTerminalRuleCall_1_0_1() { return cEntityEntityIDTerminalRuleCall_1_0_1; }
		
		//(array?='[' length=INT? ']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//array?='['
		public Assignment getArrayAssignment_2_0() { return cArrayAssignment_2_0; }
		
		//'['
		public Keyword getArrayLeftSquareBracketKeyword_2_0_0() { return cArrayLeftSquareBracketKeyword_2_0_0; }
		
		//length=INT?
		public Assignment getLengthAssignment_2_1() { return cLengthAssignment_2_1; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_2_1_0() { return cLengthINTTerminalRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
	}
	public class LookupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.Lookup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cTypeAlternatives_1_0 = (Alternatives)cTypeAssignment_1.eContents().get(0);
		private final RuleCall cTypeLookupIntParserRuleCall_1_0_0 = (RuleCall)cTypeAlternatives_1_0.eContents().get(0);
		private final RuleCall cTypeLookupStringParserRuleCall_1_0_1 = (RuleCall)cTypeAlternatives_1_0.eContents().get(1);
		
		//Lookup:
		//	name=ID type=(LookupInt | LookupString);
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID type=(LookupInt | LookupString)
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//type=(LookupInt | LookupString)
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//(LookupInt | LookupString)
		public Alternatives getTypeAlternatives_1_0() { return cTypeAlternatives_1_0; }
		
		//LookupInt
		public RuleCall getTypeLookupIntParserRuleCall_1_0_0() { return cTypeLookupIntParserRuleCall_1_0_0; }
		
		//LookupString
		public RuleCall getTypeLookupStringParserRuleCall_1_0_1() { return cTypeLookupStringParserRuleCall_1_0_1; }
	}
	public class LookupIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.LookupInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIntegerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDescriptionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_1_0 = (RuleCall)cDescriptionAssignment_1.eContents().get(0);
		private final Keyword cValuesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValuesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValuesLookupIntValueParserRuleCall_4_0 = (RuleCall)cValuesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValuesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValuesLookupIntValueParserRuleCall_5_1_0 = (RuleCall)cValuesAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//LookupInt:
		//	'integer' description=STRING? 'values' '{' values+=LookupIntValue ("," values+=LookupIntValue)* '}' ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'integer' description=STRING? 'values' '{' values+=LookupIntValue ("," values+=LookupIntValue)* '}' ';'
		public Group getGroup() { return cGroup; }
		
		//'integer'
		public Keyword getIntegerKeyword_0() { return cIntegerKeyword_0; }
		
		//description=STRING?
		public Assignment getDescriptionAssignment_1() { return cDescriptionAssignment_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_1_0() { return cDescriptionSTRINGTerminalRuleCall_1_0; }
		
		//'values'
		public Keyword getValuesKeyword_2() { return cValuesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//values+=LookupIntValue
		public Assignment getValuesAssignment_4() { return cValuesAssignment_4; }
		
		//LookupIntValue
		public RuleCall getValuesLookupIntValueParserRuleCall_4_0() { return cValuesLookupIntValueParserRuleCall_4_0; }
		
		//("," values+=LookupIntValue)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//values+=LookupIntValue
		public Assignment getValuesAssignment_5_1() { return cValuesAssignment_5_1; }
		
		//LookupIntValue
		public RuleCall getValuesLookupIntValueParserRuleCall_5_1_0() { return cValuesLookupIntValueParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
	}
	public class LookupStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.LookupString");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStringKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDescriptionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_1_0 = (RuleCall)cDescriptionAssignment_1.eContents().get(0);
		private final Keyword cValuesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValuesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValuesLookupStringValueParserRuleCall_4_0 = (RuleCall)cValuesAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValuesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValuesLookupStringValueParserRuleCall_5_1_0 = (RuleCall)cValuesAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cSemicolonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//LookupString:
		//	'string' description=STRING? 'values' '{' values+=LookupStringValue ("," values+=LookupStringValue)* '}' ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'string' description=STRING? 'values' '{' values+=LookupStringValue ("," values+=LookupStringValue)* '}' ';'
		public Group getGroup() { return cGroup; }
		
		//'string'
		public Keyword getStringKeyword_0() { return cStringKeyword_0; }
		
		//description=STRING?
		public Assignment getDescriptionAssignment_1() { return cDescriptionAssignment_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_1_0() { return cDescriptionSTRINGTerminalRuleCall_1_0; }
		
		//'values'
		public Keyword getValuesKeyword_2() { return cValuesKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//values+=LookupStringValue
		public Assignment getValuesAssignment_4() { return cValuesAssignment_4; }
		
		//LookupStringValue
		public RuleCall getValuesLookupStringValueParserRuleCall_4_0() { return cValuesLookupStringValueParserRuleCall_4_0; }
		
		//("," values+=LookupStringValue)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//values+=LookupStringValue
		public Assignment getValuesAssignment_5_1() { return cValuesAssignment_5_1; }
		
		//LookupStringValue
		public RuleCall getValuesLookupStringValueParserRuleCall_5_1_0() { return cValuesLookupStringValueParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//';'
		public Keyword getSemicolonKeyword_7() { return cSemicolonKeyword_7; }
	}
	public class LookupIntValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.LookupIntValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLookupIntValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LookupIntValue:
		//	{LookupIntValue}
		//	'(' value=INT ':' description=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{LookupIntValue} '(' value=INT ':' description=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{LookupIntValue}
		public Action getLookupIntValueAction_0() { return cLookupIntValueAction_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_0() { return cDescriptionSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class LookupStringValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.ulm.metaulm.xtext.UlmDsl2.LookupStringValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLookupStringValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LookupStringValue:
		//	{LookupStringValue}
		//	'(' value=STRING ':' description=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//{LookupStringValue} '(' value=STRING ':' description=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//{LookupStringValue}
		public Action getLookupStringValueAction_0() { return cLookupStringValueAction_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_0() { return cDescriptionSTRINGTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	
	
	private final ModelElements pModel;
	private final ContextElements pContext;
	private final VersionElements pVersion;
	private final AttributeElements pAttribute;
	private final AttributeTypeElements pAttributeType;
	private final AttributeStringTypeElements pAttributeStringType;
	private final AttributeDecimalTypeElements pAttributeDecimalType;
	private final EntityElements pEntity;
	private final FeatureElements pFeature;
	private final FeatureTypeElements pFeatureType;
	private final AttributeFeatureTypeElements pAttributeFeatureType;
	private final EntityFeatureTypeElements pEntityFeatureType;
	private final LookupElements pLookup;
	private final LookupIntElements pLookupInt;
	private final LookupStringElements pLookupString;
	private final LookupIntValueElements pLookupIntValue;
	private final LookupStringValueElements pLookupStringValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public UlmDsl2GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pContext = new ContextElements();
		this.pVersion = new VersionElements();
		this.pAttribute = new AttributeElements();
		this.pAttributeType = new AttributeTypeElements();
		this.pAttributeStringType = new AttributeStringTypeElements();
		this.pAttributeDecimalType = new AttributeDecimalTypeElements();
		this.pEntity = new EntityElements();
		this.pFeature = new FeatureElements();
		this.pFeatureType = new FeatureTypeElements();
		this.pAttributeFeatureType = new AttributeFeatureTypeElements();
		this.pEntityFeatureType = new EntityFeatureTypeElements();
		this.pLookup = new LookupElements();
		this.pLookupInt = new LookupIntElements();
		this.pLookupString = new LookupStringElements();
		this.pLookupIntValue = new LookupIntValueElements();
		this.pLookupStringValue = new LookupStringValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.ulm.metaulm.xtext.UlmDsl2".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	'model' name=ID '{'
	//	contexts+=Context*
	//	'}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Context:
	//	'context' name=ID version=Version '{' ('attributes' '{'
	//	attributes+=Attribute*
	//	'}')? ('lookups' '{'
	//	lookups+=Lookup*
	//	'}')? ('entities' '{'
	//	entities+=Entity*
	//	'}')?
	//	'}';
	public ContextElements getContextAccess() {
		return pContext;
	}
	
	public ParserRule getContextRule() {
		return getContextAccess().getRule();
	}
	
	//Version:
	//	INT '.' INT '.' INT;
	public VersionElements getVersionAccess() {
		return pVersion;
	}
	
	public ParserRule getVersionRule() {
		return getVersionAccess().getRule();
	}
	
	//Attribute:
	//	name=ID type=(AttributeType | AttributeStringType | AttributeDecimalType) desc=STRING? ';';
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//AttributeType:
	//	name=('int' | 'boolean' | 'date' | 'datetime' | 'timestamp');
	public AttributeTypeElements getAttributeTypeAccess() {
		return pAttributeType;
	}
	
	public ParserRule getAttributeTypeRule() {
		return getAttributeTypeAccess().getRule();
	}
	
	//AttributeStringType:
	//	name='string' (array?='[' length=INT ']')?;
	public AttributeStringTypeElements getAttributeStringTypeAccess() {
		return pAttributeStringType;
	}
	
	public ParserRule getAttributeStringTypeRule() {
		return getAttributeStringTypeAccess().getRule();
	}
	
	//AttributeDecimalType:
	//	name='decimal' (array?='[' scale=INT (',' precision=INT)? ']')?;
	public AttributeDecimalTypeElements getAttributeDecimalTypeAccess() {
		return pAttributeDecimalType;
	}
	
	public ParserRule getAttributeDecimalTypeRule() {
		return getAttributeDecimalTypeAccess().getRule();
	}
	
	//Entity:
	//	type=('data' | 'static' | 'lookup')? name=ID desc=STRING? ('extends' superType=[Entity])? '{'
	//	features+=Feature*
	//	'}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//Feature:
	//	type=FeatureType
	//	mandatory?='mandatory'?
	//	identifier?='identifier'? ('as' name=ID)?
	//	';';
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}
	
	//FeatureType:
	//	type=(AttributeFeatureType | EntityFeatureType);
	public FeatureTypeElements getFeatureTypeAccess() {
		return pFeatureType;
	}
	
	public ParserRule getFeatureTypeRule() {
		return getFeatureTypeAccess().getRule();
	}
	
	//AttributeFeatureType:
	//	attribute=[Attribute] ('bounded' lookup=[Lookup])?;
	public AttributeFeatureTypeElements getAttributeFeatureTypeAccess() {
		return pAttributeFeatureType;
	}
	
	public ParserRule getAttributeFeatureTypeRule() {
		return getAttributeFeatureTypeAccess().getRule();
	}
	
	//EntityFeatureType:
	//	'references' entity=[Entity] (array?='[' length=INT? ']')?;
	public EntityFeatureTypeElements getEntityFeatureTypeAccess() {
		return pEntityFeatureType;
	}
	
	public ParserRule getEntityFeatureTypeRule() {
		return getEntityFeatureTypeAccess().getRule();
	}
	
	//Lookup:
	//	name=ID type=(LookupInt | LookupString);
	public LookupElements getLookupAccess() {
		return pLookup;
	}
	
	public ParserRule getLookupRule() {
		return getLookupAccess().getRule();
	}
	
	//LookupInt:
	//	'integer' description=STRING? 'values' '{' values+=LookupIntValue ("," values+=LookupIntValue)* '}' ';';
	public LookupIntElements getLookupIntAccess() {
		return pLookupInt;
	}
	
	public ParserRule getLookupIntRule() {
		return getLookupIntAccess().getRule();
	}
	
	//LookupString:
	//	'string' description=STRING? 'values' '{' values+=LookupStringValue ("," values+=LookupStringValue)* '}' ';';
	public LookupStringElements getLookupStringAccess() {
		return pLookupString;
	}
	
	public ParserRule getLookupStringRule() {
		return getLookupStringAccess().getRule();
	}
	
	//LookupIntValue:
	//	{LookupIntValue}
	//	'(' value=INT ':' description=STRING ')';
	public LookupIntValueElements getLookupIntValueAccess() {
		return pLookupIntValue;
	}
	
	public ParserRule getLookupIntValueRule() {
		return getLookupIntValueAccess().getRule();
	}
	
	//LookupStringValue:
	//	{LookupStringValue}
	//	'(' value=STRING ':' description=STRING ')';
	public LookupStringValueElements getLookupStringValueAccess() {
		return pLookupStringValue;
	}
	
	public ParserRule getLookupStringValueRule() {
		return getLookupStringValueAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
