/*
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUlmDsl2ScopeProvider extends DelegatingScopeProvider {
}
