/**
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext;

import org.ulm.metaulm.xtext.AbstractUlmDsl2RuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UlmDsl2RuntimeModule extends AbstractUlmDsl2RuntimeModule {
}
