/**
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext;

import org.ulm.metaulm.xtext.UlmDsl2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class UlmDsl2StandaloneSetup extends UlmDsl2StandaloneSetupGenerated {
  public static void doSetup() {
    new UlmDsl2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
