/*
 * generated by Xtext 2.12.0
 */
package org.ulm.metaulm.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UlmDsl2RuntimeModule extends AbstractUlmDsl2RuntimeModule {
}
